### ISSUE TITLE
default route is set to "/react-miniproject" from '/'

### ISSUE THREAD

**Issue by abhaybhatt** [ashutosh44ks/react-miniprojects#1]
change homage in package.json to 
"homepage": "https://ashutosh44ks.github.io/",

**Comment by ashutosh44ks** [comment]
Fixed the issue. See in the recent commit.
Basically, 
In package.json, homepage should have the repository name appended to it
In the App,  any Route link we have, we need to change e.g. path="/page2" to path="/<Repository-Name>/page2"
